environment:
  matrix:
    - PYTHON_VERSION: 3.7
      MINICONDA: C:\Miniconda3-x64

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda config --set channel_priority strict
  - conda create --yes --name testenv poppler
  - activate testenv

build: off

test_script:
  - python setup.py test
